language: python
python:
- '3.3'
- '3.4'
- '3.5'
addons:
  postgresql: '9.4'
install:
- pip install -r requirements.txt
- pip install -r requirements/development.txt
- pip install coveralls
before_script:
- psql -c 'CREATE DATABASE awesome_resume;' -U postgres
script:
- make migrate
- make test
after_success:
- coveralls
